# 특정 서비스가 아닌 공통적으로 사용하는 속성을 정의
# 모든 Service가 바라보게 된다.
# token:
#   expiration_time: 86400000
#   secret: my_token_native_application_changed_#2
token:
  expiration_time: 86400000
  secret: '{cipher}AQAv82VOSNUx0Jkj1Wd1G6vQG0oi8SwCVksHfUX9aLnhjA1VutFoqVmSQKwX7z1q8Y/0Rfc4N3mxnEUKm05jrGQ8ZusRKBABX4HmPMYtSM/rtOEi0vzboqr4mR+x+FqJjkTQn1TXTsUZunuDqOAYkoXhSBQWrAFPbSRTcwfr12lp4awSzHEBz1nDPrhRvBMI/VOXZWobtLSD2+UENlhneHFFchitVUFr2ZsKhj4N48Ct0q7gcc4ANTL7dv8BO66NuFTYj80qOr6GJL8f1lypz0hqJCkwLmkzSRbOM4Z3FNbb+DKq0zWLoJEFAHo6HR1QBUlYZd8XfGchG+7x/K419Ff1T1jA5ghw1O0uUgGShk9M4h0xcmR7+PJCoYzsDC+7iMR+mZj0WtAfVKZYnMedCrow'

gateway:
  ip: 192.168.31.1

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders